/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package briscola;

import briscola.card.Suit;
import briscola.card.Value;
import briscola.deck.CardShuffler;
import briscola.deck.Deck;
import briscola.game.Dice;
import briscola.game.Game;
import briscola.player.Player;
import com.google.common.flogger.FluentLogger;

import java.util.Map;
import java.util.logging.LogManager;

public class App {

    static {
        System.setProperty("java.util.logging.SimpleFormatter.format", "%5$s%n");
    }

    public static void main(String[] args) {
        final Map<String, Integer> result = new Game(
                new Player("Omar"),
                new Player("Rita"),
                new Deck(new CardShuffler(), Value.values(), Suit.values()),
                new Dice(6)
        ).play();
        System.out.println(result);
    }
}
